### ISSUE TITLE
Create react app + react native web+ react-native-status-bar-height

### ISSUE THREAD

**Issue by startupgurukul** [ovr/react-native-status-bar-height#10]
Hello Dmitry,
When react-native-status-bar-height is  imported  in a create react app setup, this error is encountered

react-native-status-bar-height/index.js: Unexpected token, expected "," (18:46)
> 18 | export function getStatusBarHeight(skipAndroid: boolean = false): number {

Here is a link to reproduce the issue, 
https://codesandbox.io/s/rwwp95zw34

Thank you.

**Comment by ovr** [comment]
Hey! It's because you didnt use .babel-preset-flow to strip flow types, but anyway I extract theys to own file

Fixed in `v2.2.1`

Thanks

**Comment by startupgurukul** [comment]
Thank you, issue resolved
