### ISSUE TITLE
Height is always 0 for android

### ISSUE THREAD

**Issue by TomMahle** [ovr/react-native-status-bar-height#2]
react-native's StatusBar.currentHeight ( https://facebook.github.io/react-native/docs/statusbar.html ) would be a more appropriate thing to return, as it determines the android status bar height.

**Comment by ovr** [comment]
Hey @TomMahle, can you share me any device with status bar not `0`?

Thank you!

**Comment by TomMahle** [comment]
Hi @ovr I'm actually unsure what was causing the issue I was seeing when I submitted this, but presently my codebase is directly using your library with no separate accounting for android status bar height. This issue can likely be closed. Thanks for following up and helping maintain this useful library!

**Comment by ovr** [comment]
Should be closed due a `2.0.0` release!

![image](https://user-images.githubusercontent.com/572096/35205586-cb43601a-ff79-11e7-9ba7-491162a159b1.png)
