### ISSUE TITLE
What exactly is skipAndroid value for?

### ISSUE THREAD

**Issue by mezod** [ovr/react-native-status-bar-height#5]
In my android device I seem to need marginTop: 0 for it to behave as I expect. However, this library returns a value of 25.333, which leaves white space between android's statusbar and the beginning of my app. I have read there's this skipAndroid value that sets it to 0, but, what exactly is this? It means it will ignore every other statusbar height for any other android?

**Comment by ovr** [comment]
@mezod `skipAndroid` is needed to skip value for Android, with `skipAndroid` this will be `0` all time

**Comment by mezod** [comment]
I see, so the value for android is used for when StatusBar is set to translucent, right? Thanks!

**Comment by ovr** [comment]
I am going to close this issue, because there is answer ;)

**Comment by busterbogheart** [comment]
Might be nice to have this in the Readme too
