### ISSUE TITLE
Fails on new iPhone Xs Max

### ISSUE THREAD

**Issue by iRoachie** [ovr/react-native-status-bar-height#7]
Returns the incorrect height on iPhone Xs Max. See similar issues around the community.
https://github.com/react-navigation/react-navigation/issues/4985

This is because iPhone Xs Max has the same dpi as the iPhone X but the height and width are different so the library you depend on [react-native-iphone-x-helper](https://github.com/ptelad/react-native-iphone-x-helper/blob/master/index.js#L9) fails.

![simulator screen shot - iphone xs max - 2018-09-21 at 05 26 04](https://user-images.githubusercontent.com/5962998/45872779-d866ee80-bd5e-11e8-9777-111e4f9fee7a.png)

**Comment by iRoachie** [comment]
Open PR is here https://github.com/ptelad/react-native-iphone-x-helper/issues/6

**Comment by ovr** [comment]
I drop usage of `react-native-iphone-x-helper` inside `master`
Support for new iPhone models, added in https://github.com/ovr/react-native-status-bar-height/commit/329b32709230f17638353e2cf761cef8bba873a4

Released `v2.1.0`, Thanks
